### ISSUE TITLE
userMapping

### ISSUE THREAD

**Issue by MrElie** [Daiigr/GPT3.5-DiscordChatbot#7]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "Bot.py", line 101, in on_message
    user = user_json_parser.getUserBy(message.author.id)
AttributeError: 'UserJsonParser' object has no attribute 'getUserBy'
`
i get this havbe to do with usermapping.. here is my test format to see what im doing wrong:

`125156161616, mrelie,He,ADMIN`
what am i doing wrong? the id is random numbers for privacy obv

**Comment by danielgrbacbravo** [comment]
thanks for creating a new issue, yea this is not a configuration issue on your end but a new bug from the latest commit. it should have been 'getUserByID' instead of 'getUserBy'.  i got the same error message when i tried to send a message

**Comment by danielgrbacbravo** [comment]
Fixed with commit: 736d57e

**Comment by MrElie** [comment]
another lovely addition would be the openai moderation.. do u think u can work on that if u have some free time ?

**Comment by danielgrbacbravo** [comment]
yea sure no problem, what sort of moderation would you like. you can put your feature requests in the projects page for this repo

**Comment by MrElie** [comment]
People to not be able to use hate words, sexual speech, anything that is undecent.
Do u have discord btw I'd like to have a talk with u

**Comment by MrElie** [comment]
also one last feature which is massive important.. to let it speak only in a channel given by channel id

**Comment by danielgrbacbravo** [comment]
ok no problem

**Comment by MrElie** [comment]
Can I have ur discord?

**Comment by danielgrbacbravo** [comment]
> also one last feature which is massive important.. to let it speak only in a channel given by channel id

I can add that however, it's quite useless because you can just block the discord bot from reading other channels in the server settings

**Comment by Daiigr** [comment]
> Can I have ur discord? 

Sure Daiigr#7964
